### ISSUE TITLE
Installation trouble - composer dependency resolve - guzzle

### ISSUE THREAD

**Issue by piotrkochan** [Sylake/Sylakim#11]
I want to run Sylakim, but i can't. Should I require package via composer to existing akeneo/pim-community-standard project?
If yes, then I've got:

> Using version ^0.1.0@dev for sylake/sylakim  
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)  
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for sylake/sylakim ^0.1.0@dev -> satisfiable by sylake/sylakim[0.1.x-dev].
> - Conclusion: remove guzzle/common v3.7.4
>   - Conclusion: don't install guzzle/common v3.7.4
>   - sylake/sylakim 0.1.x-dev requires guzzlehttp/guzzle ~3.8 -> satisfiable by guzzlehttp/guzzle[v3.8.0, v3.8.1].
>   - don't install guzzlehttp/guzzle v3.8.0|don't install guzzle/common v3.7.4
>   - don't install guzzlehttp/guzzle v3.8.1|don't install guzzle/common v3.7.4
>   - Installation request for guzzle/common == 3.7.4.0 -> satisfiable by guzzle/common[v3.7.4].

How can I solve that?

**Comment by aRn0D** [comment]
@piotrkochan This bundle does not work!
@michalmarcinkowski When do you plan to push the first version?
