### ISSUE TITLE
How far is this connector?

### ISSUE THREAD

**Issue by jeroendesloovere** [Sylake/Sylakim#13]
Hi, a connection between Akeneo PIM and Sylius would be awesome.
How far is this repository in doing this?

**Comment by michalmarcinkowski** [comment]
There are a lot of changes and BC breaks in Sylius at that moment, so for our side the work on connector will be postponed to at least Sylius 1.0-beta. For one project we used https://github.com/Lakion/sylius-api-php and wrote some custom normalizers, processors and writers using Sylius API.

**Comment by nidup** [comment]
Hi guys, @fitn you could be interested by this discussion :)

**Comment by fitn** [comment]
@nidup Yep yep I'm already in ;)

**Comment by krafas** [comment]
Sylius released beta: https://github.com/Sylius/Sylius/releases/tag/v1.0.0-beta.1

**Comment by michalmarcinkowski** [comment]
We will start working on integrations just after `v1.0.0-beta.2` tag, expect it this month! Akeneo PIM is high on our list so we hope to get a project during which we could integrate this two systems 😉

**Comment by jmleroux** [comment]
Do not hesitate to join us at marketplace@akeneo.com to discuss about this connector.
If it is about importing product data into Sylius, we recommend to parse the native Akeneo export files in a Sylius module instead of relying on a bundle on Akeneo side.

**Comment by michalmarcinkowski** [comment]
Thanks for your willingness to cooperate! We will for sure get in touch with you and the community before proceeding with any work :)

**Comment by fitn** [comment]
@michalmarcinkowski Could we plan a meeting to discuss on next steps?
I worked in Akeneo Marketplace team but I think that @jjanvier, @aRn0D and myself would be happy to help on that subject too :)

**Comment by jjanvier** [comment]
👍
That's why I made some PRs on the Sylius API ^^

**Comment by jmleroux** [comment]
> I worked in Akeneo Marketplace team

oh crap, i didn't know you were not in my team anymore :)

**Comment by pjedrzejewski** [comment]
We are restarting the development of this connector, so you can keep an eye on this repository to see the progress. :)
